server:
  port: 8081
spring:
  application:
    name: openmuc-service
  datasource:
    url: jdbc:postgresql://192.168.4.45:5432/openmuc?options=-c%20timezone=Asia/Ho_Chi_Minh
    driver-class-name: org.postgresql.Driver
    username: openmuc_user
    password: openmuc
    hikari:
      pool-name: OpenmucPool
      maximum-pool-size: 50 # connections = (core_count * 2) + effective_spindle_count
      minimum-idle: 20
      idle-timeout: 60000
      max-lifetime: 1200000
      connection-timeout: 5000
      leak-detection-threshold: 20000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: Asia/Ho_Chi_Minh
