spring:
  application:
    name: openmuc-service
  datasource:
    url: jdbc:postgresql://192.168.4.45:5432/openmuc
    driver-class-name: org.postgresql.Driver
    username: openmuc_user
    password: openmuc
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
